default:
  image: node:current-alpine
  before_script:
    - PATH=$PATH:/home/node/.npm-global/bin

stages:
  - lint

markdownlint:
  stage: lint
  script:
    - npm install -g markdownlint-cli
    - markdownlint '**/*.md'

csslint:
  stage: lint
  script:
    - npm install -g stylelint --save-dev
    - stylelint "**/*.css"

htmllint:
  stage: lint
  script:
    - npm install -g htmlhint --save-dev
    - htmlhint "**/*.html"
