default:
  image: node:current-alpine

variables:
  GIT_STRATEGY: fetch
  GIT_SUBMODULE_STRATEGY: none

stages:
  - lint

default:
  before_script:
    - ENV PATH=$PATH:/home/node/.npm-global/bin
    - node --version
    - npm --version

testlint:
  stage: lint
  script:
    - echo "test lint"
