default:
  image: node:current-alpine

variables:
  GIT_STRATEGY: fetch
  GIT_SUBMODULE_STRATEGY: none

stages:
  - lint

markdownlint:
  stage: lint
  script:
    - npm install -g markdownlint-cli
    - markdownlint '**/*.md'

csslint:
  stage: lint
  script:
    - npm install stylelint --save-dev
    - stylelint "**/*.css"

htmllint:
  stage: lint
  script:
    - npm install htmlhint --save-dev
    - htmlhint "**/*.html"
